spring.application.name=api-gateway
server.port=8080

# Routes
spring.cloud.gateway.routes[0].id=auth-route
spring.cloud.gateway.routes[0].uri=${AUTH_SERVICE_URL:http://localhost:8081}
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.routes[1].id=event-route
spring.cloud.gateway.routes[1].uri=${EVENT_SERVICE_URL:http://localhost:8083}
spring.cloud.gateway.routes[1].predicates[0]=Path=/events/**

spring.cloud.gateway.routes[2].id=user-route
spring.cloud.gateway.routes[2].uri=${USER_SERVICE_URL:http://localhost:8082}
spring.cloud.gateway.routes[2].predicates[0]=Path=/users/**

spring.cloud.gateway.routes[3].id=inscription-route
spring.cloud.gateway.routes[3].uri=${INSCRIP_SERVICE_URL:http://localhost:8084}
spring.cloud.gateway.routes[3].predicates[0]=Path=/inscriptions/**

spring.cloud.gateway.routes[4].id=notification-route
spring.cloud.gateway.routes[4].uri=${NOTIFICATION_SERVICE_URL:http://localhost:8085}
spring.cloud.gateway.routes[4].predicates[0]=Path=/notifications/**

# CORS settings for Frontend
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://127.0.0.1:3000,http://localhost:3000
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allow-credentials=true

logging.level.org.springframework.cloud.gateway=DEBUG
